import { CommentaryEvent } from "./types";

export const commentaryTexts: Record<CommentaryEvent, string[]> = {
  start: [
    "The players are out on the field, and we're ready to start the match!",
    "The umpires have taken their positions, and the game is about to begin.",
    "The crowd is buzzing with excitement as the first ball is about to be bowled.",
    "It's a beautiful day for cricket, and the match is about to start.",
    "The captains have shaken hands, and the players are taking their positions.",
    "The opening batsmen are walking out to the middle, and the match is set to begin.",
    "The bowler is marking his run-up, and we're moments away from the first delivery.",
    "The fielders are in position, and the umpire signals the start of the match.",
    "The national anthems have been sung, and the match is ready to commence.",
    "The toss has been won, and the players are ready to get the game underway.",
  ],
  secondInnings: [
    "The players are back on the field for the second innings.",
    "The chase is on as the second innings begins.",
    "The fielding team is ready, and the batsmen are walking out for the second innings.",
    "The second innings is about to start, and the crowd is on the edge of their seats.",
    "The bowlers are warming up, and the second innings is set to begin.",
    "The first ball of the second innings is about to be bowled.",
    "The players are taking their positions for the second innings.",
    "The second innings is underway, and the fielders are in position.",
    "The batsmen are ready, and the second innings is about to start.",
    "The second innings begins, and the crowd is eagerly watching.",
  ],
  dot: [
    "And it's a dot ball, no run taken.",
    "The batsman plays and misses, dot ball.",
    "A good delivery, no run scored.",
    "Defended back to the bowler, no run.",
    "The batsman leaves it alone, dot ball.",
    "A tight delivery, no scoring opportunity.",
    "Played straight to the fielder, no run.",
    "The batsman is beaten by that one, dot ball.",
    "A near miss! But it's a dot ball.",
    "Excellent bowling, no run given.",
    "The batsman is watchful, plays out a dot.",
    "A risky shot, but it's still a dot ball.",
  ],
  single: [
    "Quick single taken, good running between the wickets.",
    "The batsman pushes it into the gap for a single.",
    "A gentle tap and they scamper through for one.",
    "Nudged away for a single, keeping the scoreboard ticking.",
    "Smart cricket, rotating the strike with a single.",
    "Just a single, but every run counts in this game.",
    "The fielder fumbles, allowing a quick single.",
    "A well-judged single, putting pressure on the field.",
    "Pushed into the covers for a comfortable single.",
    "The batsman works it fine for a single.",
    "A delicate touch, and they take a quick single.",
    "Flicked off the pads for a single.",
  ],
  double: [
    "Good running! They've managed to squeeze out two runs.",
    "Pushed into the gap, and they come back for a second.",
    "The batsmen are quick between the wickets, taking two.",
    "A misfield allows them to come back for the second run.",
    "Excellent judgment, they've stolen two runs there.",
    "The throw is a bit wide, and they complete two runs.",
    "Smart cricket, turning one into two with good running.",
    "They push hard and successfully complete two runs.",
    "A risky second run, but they make it safely.",
    "The fielder was slow to react, allowing two runs.",
    "Good placement and running, two runs added to the total.",
    "They've caught the fielders napping and taken two!",
  ],
  triple: [
    "Brilliant running! They've managed to get three runs.",
    "The ball races to the deep, and they run three.",
    "A fumble in the outfield, and they sprint back for the third!",
    "Excellent judgment of the run, they've taken three.",
    "The fielder's throw is off target, allowing a third run.",
    "Aggressive running between the wickets, three taken!",
    "They've pushed the fielders to the limit, completing three runs.",
    "A rare three runs in cricket, great effort from the batsmen.",
    "The batsmen are really putting pressure on the field with three runs.",
    "Quick thinking and quicker legs, they've run three!",
    "The fielders were caught off guard, and the batsmen snatch three.",
    "A daring dash for the third run, and they make it!",
  ],
  four: [
    "Cracking shot! That races away to the boundary for four.",
    "Beautifully timed, and it finds the gap for four runs.",
    "The batsman punishes that loose delivery, four runs!",
    "Elegant stroke-play, and it's four more to the total.",
    "That's been hammered away for a boundary!",
    "A delightful shot that evades the fielders and runs for four.",
    "The batsman capitalizes on that one, sending it to the rope.",
    "Textbook shot, and it results in a lovely four.",
    "The field is breached, and that's four more runs.",
    "A clinical strike, and it races away for four.",
    "The batsman finds the gap perfectly, that's four runs.",
    "Sweetly timed, and it speeds to the boundary for four.",
  ],
  six: [
    "Massive hit! That's sailed over the ropes for six!",
    "What a shot! The ball disappears into the crowd for six.",
    "The batsman has really got hold of that one, it's a huge six!",
    "That's been launched into orbit! Six runs!",
    "A mighty blow! The ball is still climbing as it crosses the boundary.",
    "Incredible power! That's a massive six!",
    "The crowd goes wild as that sails over for six!",
    "No half measures there, it's a full-blooded six!",
    "That's been dispatched with authority! Six runs!",
    "The batsman makes it look easy, smashing that for six.",
    "A clean strike, and it's a maximum! Six runs!",
    "The fielder on the boundary can only watch that sail over for six.",
  ],
  wicket: [
    "Oh no! The batsman has to go, that's out!",
    "Wicket! A crucial breakthrough for the bowling side.",
    "That's the end of a fine innings, the batsman is dismissed.",
    "The bowler strikes! That's a big wicket for the team.",
    "Disaster for the batting side, they've lost another wicket.",
    "The fielders are ecstatic, they've got their man!",
    "A moment of brilliance in the field, and the batsman is out!",
    "That's a killer blow, the set batsman is walking back.",
    "The bowler's persistence pays off, it's a wicket!",
    "A lapse in concentration, and it costs the batsman his wicket.",
    "The fielding side is jubilant, they've broken through!",
    "What a delivery! The batsman had no answer to that one.",
  ],
};
