import { CommentaryEvent } from '../types/types';

export const commentaryTexts: Record<CommentaryEvent, string[]> = {
	start: [
		"The players are out on the field, and we're ready to start the match!",
		'The umpires have taken their positions, and the game is about to begin.',
		'The crowd is buzzing with excitement as the first ball is about to be bowled.',
		"It's a beautiful day for cricket, and the match is about to start.",
		'The captains have shaken hands, and the players are taking their positions.',
		'The opening batsmen are walking out to the middle, and the match is set to begin.',
		"The bowler is marking his run-up, and we're moments away from the first delivery.",
		'The fielders are in position, and the umpire signals the start of the match.',
		'The national anthems have been sung, and the match is ready to commence.',
		'The toss has been won, and the players are ready to get the game underway.',
	],
	secondInnings: [
		'The players are back on the field for the second innings.',
		'The chase is on as the second innings begins.',
		'The fielding team is ready, and the batsmen are walking out for the second innings.',
		'The second innings is about to start, and the crowd is on the edge of their seats.',
		'The bowlers are warming up, and the second innings is set to begin.',
		'The first ball of the second innings is about to be bowled.',
		'The players are taking their positions for the second innings.',
		'The second innings is underway, and the fielders are in position.',
		'The batsmen are ready, and the second innings is about to start.',
		'The second innings begins, and the crowd is eagerly watching.',
	],
	dot: [
		"And it's a dot ball, no run taken.",
		'The batsman plays and misses, dot ball.',
		'A good delivery, no run scored.',
		'Defended back to the bowler, no run.',
		'The batsman leaves it alone, dot ball.',
		'A tight delivery, no scoring opportunity.',
		'Played straight to the fielder, no run.',
		'The batsman is beaten by that one, dot ball.',
		"A near miss! But it's a dot ball.",
		'Excellent bowling, no run given.',
		'The batsman is watchful, plays out a dot.',
		"A risky shot, but it's still a dot ball.",
	],
	single: [
		'Quick single taken, good running between the wickets.',
		'The batsman pushes it into the gap for a single.',
		'A gentle tap and they scamper through for one.',
		'Nudged away for a single, keeping the scoreboard ticking.',
		'Smart cricket, rotating the strike with a single.',
		'Just a single, but every run counts in this game.',
		'The fielder fumbles, allowing a quick single.',
		'A well-judged single, putting pressure on the field.',
		'Pushed into the covers for a comfortable single.',
		'The batsman works it fine for a single.',
		'A delicate touch, and they take a quick single.',
		'Flicked off the pads for a single.',
	],
	double: [
		"Good running! They've managed to squeeze out two runs.",
		'Pushed into the gap, and they come back for a second.',
		'The batsmen are quick between the wickets, taking two.',
		'A misfield allows them to come back for the second run.',
		"Excellent judgment, they've stolen two runs there.",
		'The throw is a bit wide, and they complete two runs.',
		'Smart cricket, turning one into two with good running.',
		'They push hard and successfully complete two runs.',
		'A risky second run, but they make it safely.',
		'The fielder was slow to react, allowing two runs.',
		'Good placement and running, two runs added to the total.',
		"They've caught the fielders napping and taken two!",
	],
	triple: [
		"Brilliant running! They've managed to get three runs.",
		'The ball races to the deep, and they run three.',
		'A fumble in the outfield, and they sprint back for the third!',
		"Excellent judgment of the run, they've taken three.",
		"The fielder's throw is off target, allowing a third run.",
		'Aggressive running between the wickets, three taken!',
		"They've pushed the fielders to the limit, completing three runs.",
		'A rare three runs in cricket, great effort from the batsmen.',
		'The batsmen are really putting pressure on the field with three runs.',
		"Quick thinking and quicker legs, they've run three!",
		'The fielders were caught off guard, and the batsmen snatch three.',
		'A daring dash for the third run, and they make it!',
	],
	four: [
		'Cracking shot! That races away to the boundary for four.',
		'Beautifully timed, and it finds the gap for four runs.',
		'The batsman punishes that loose delivery, four runs!',
		"Elegant stroke-play, and it's four more to the total.",
		"That's been hammered away for a boundary!",
		'A delightful shot that evades the fielders and runs for four.',
		'The batsman capitalizes on that one, sending it to the rope.',
		'Textbook shot, and it results in a lovely four.',
		"The field is breached, and that's four more runs.",
		'A clinical strike, and it races away for four.',
		"The batsman finds the gap perfectly, that's four runs.",
		'Sweetly timed, and it speeds to the boundary for four.',
	],
	six: [
		"Massive hit! That's sailed over the ropes for six!",
		'What a shot! The ball disappears into the crowd for six.',
		"The batsman has really got hold of that one, it's a huge six!",
		"That's been launched into orbit! Six runs!",
		'A mighty blow! The ball is still climbing as it crosses the boundary.',
		"Incredible power! That's a massive six!",
		'The crowd goes wild as that sails over for six!',
		"No half measures there, it's a full-blooded six!",
		"That's been dispatched with authority! Six runs!",
		'The batsman makes it look easy, smashing that for six.',
		"A clean strike, and it's a maximum! Six runs!",
		'The fielder on the boundary can only watch that sail over for six.',
	],
	wicket: [
		"Oh no! The batsman has to go, that's out!",
		'Wicket! A crucial breakthrough for the bowling side.',
		"That's the end of a fine innings, the batsman is dismissed.",
		"The bowler strikes! That's a big wicket for the team.",
		"Disaster for the batting side, they've lost another wicket.",
		"The fielders are ecstatic, they've got their man!",
		'A moment of brilliance in the field, and the batsman is out!',
		"That's a killer blow, the set batsman is walking back.",
		"The bowler's persistence pays off, it's a wicket!",
		'A lapse in concentration, and it costs the batsman his wicket.',
		"The fielding side is jubilant, they've broken through!",
		'What a delivery! The batsman had no answer to that one.',
	],
};


export const TIPS_AND_QUOTES = [
	"Don't forget to claim your daily rewards to boost your progress!",
	'Every great innings starts with a single run.',
	"In cricket, as in life, it's not about the fall. It's about how you bounce back.",
	'The pitch is your canvas, the bat your brush. Paint your masterpiece.',
	"Champions aren't made in the gym. They are made from something deep inside them - a desire, a dream, a vision.",
	'Cricket is a game of glorious uncertainties. Embrace the challenge!',
	'Timing is everything! Practice your shots in the nets to perfect your timing.',
	"A good captain knows their team. Analyze your players' strengths for the best lineup.",
	'Upgrade your gear regularly to stay competitive in tournaments.',
	'Watch out for special events to earn rare items and big rewards!',
	'Success is not final, failure is not fatal: It is the courage to continue that counts.',
	'The harder you work, the luckier you get.',
	'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.',
	"The only way to prove that you're a good sport is to lose.",
	"Winning isn't everything, but wanting to win is.",
	'In cricket, as in life, the key is to find the gaps and make them count.',
	'Remember: Even the best batsmen started with a duck. Keep swinging!',
	'Your attitude determines your direction. Stay positive, stay winning!',
	"Cricket is not just a game, it's a way of life. Live it, love it!",
	"The difference between ordinary and extraordinary is that little 'extra'. Give it your all!",
	'Pressure is a privilege - it only comes to those who earn it.',
	"In the game of cricket, and in the game of life, it's important to play with a straight bat.",
	"Don't play for survival, play for victory. Attack is sometimes the best defense!",
	'Great players are willing to give up the good to go for the great.',
	'Cricket is a game of inches. The inches we need are everywhere around us.',
	"Your biggest rival is yourself. Beat yesterday's performance today!",
	'Like in cricket, life will throw you googlies. Learn to read them and hit them out of the park!',
	'Form is temporary, class is permanent. Keep honing your skills!',
	"In cricket and in life, it's not about the size of the dog in the fight, it's about the size of the fight in the dog.",
	'Remember: Every champion was once a contender that refused to give up.',
	'Cricket is a team game. Individual brilliance wins matches, but teamwork wins championships.',
	"Stay focused, stay humble. The moment you think you've made it, that's when you start falling behind.",
	'The key to batting is rotating the strike. Keep the scoreboard ticking!',
	'Respect the game, and the game will respect you back.',
	'Like a good innings, success in life is all about building partnerships.',
	"Don't wait for the perfect moment. Take the moment and make it perfect.",
	"In cricket, as in life, it's not about how hard you can hit, it's about how hard you can get hit and keep moving forward.",
	'Your determination today leads to your success tomorrow. Keep pushing!',
	'Cricket teaches us that every ball is an opportunity. Make each one count!',
	"The pitch might change, but your commitment to excellence shouldn't. Adapt and overcome!",
];